# Generated by Django 4.2.28 on 2026-02-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='volume')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='currency')),
                ('purchase_currency', models.CharField(default='USD', max_length=10, verbose_name='purchase currency')),
                ('rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='rate')),
                ('actual_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='actual rate')),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='purchase amount')),
                ('actual_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='actual purchase amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'date'], name='purchases_p_seller__5fb814_idx')],
            },
        ),
    ]
