# Generated by Django 4.2.28 on 2026-02-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='vendor name'),
        ),
    ]
