version: '3.8'

services:
  web:
    container_name: salesly_backend
    command: python manage.py runserver 0.0.0.0:8000
    image: ntoric/salesly_backend:latest
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8110:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key_123
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=sqlite:///db.sqlite3
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - DJANGO_SUPERUSER_EMAIL=admin@salesly.com
      - DJANGO_SUPERUSER_PASSWORD=password
      - POSTGRES_SUPERUSER_PASSWORD=postgres
      - POSTGRES_SUPERUSER_USER=postgres
    env_file:
      - ENV/.backend_env

  frontend:
    container_name: salesly_frontend
    image: ntoric/salesly_frontend:latest
    ports:
      - "3110:80"
    depends_on:
      - web
    env_file:
      - ENV/.frontend_env
