# Generated by Django 4.2.28 on 2026-02-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='volume')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='currency')),
                ('sale_currency', models.CharField(default='USD', max_length=10, verbose_name='sale currency')),
                ('rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='rate')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='district')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('pincode', models.CharField(blank=True, max_length=20, verbose_name='pincode')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
