# Generated by Django 4.2.28 on 2026-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer name'),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile number'),
        ),
    ]
