# Generated by Django 4.2.28 on 2026-02-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_customer_name_address_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address_line_1',
        ),
    ]
